<a href="https://colab.research.google.com/github/Himanshu0518/Machine-Learning/blob/main/Numpy0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python

Numpy is a fundamental package for scientific computing in python supporting for large , mullti-dimensional array and matrices , along with collection of mathematical functions to operate

Advantages of Numpy Arrays :
1. Allows several Mathematical Operations
2. Faster Operations




In [ ]:
import numpy as np

List vs Numpy - Time taken

In [ ]:
from time import process_time

Time taken by a List

In [ ]:
python_list = [i for i in range (1000)]

st_time = process_time()
pyython_list = [i+5 for i in  python_list]
en_time = process_time()
print(en_time - st_time)


0.00018386799999969838


In [ ]:
np_array = np.array([i for i in range (1000)])
st_time = process_time()
np_array += 5
en_time = process_time()
print(en_time-st_time)

0.0016403640000000053


Numpy arrays

In [ ]:
# lists
list1 = [1,2,3,4]
print(list1)
type(list1)

[1, 2, 3, 4]


list

In [ ]:
# numpy array
np_array = np.array([1,2,3,4])
print(np_array)
type(np_array)

[1 2 3 4]


numpy.ndarray

In [ ]:
# creating 1 dim array
a = np.array([1,2,3,4])
print(a) ;
a.shape

[1 2 3 4]


(4,)

In [ ]:
# creating 2D numpy array
b = np.array([(1,2,3,4),(3,4,5,8)])
print(b) ;
b.shape

[[1 2 3 4]
 [3 4 5 8]]


(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(3,4,5,8)],dtype=float)
print(c) ;
c.shape

[[1. 2. 3. 4.]
 [3. 4. 5. 8.]]


(2, 4)

Initial placeholder in numpy arrays

In [ ]:
# Create numpy arrays of Zeoes
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create a numpy arrays of ones
y = np.ones((3,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# create numpy array of specific value
z = np.full((4,5),5)
print(z)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [ ]:
# create a numpy identity matrix
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#create a numpy array with random array within [0,1]
r = np.random.random((3,4))
print(r)

[[0.29343177 0.49921912 0.41853925 0.67561385]
 [0.14987733 0.11044972 0.47040281 0.80282986]
 [0.6886251  0.12874837 0.97335296 0.59798561]]


In [ ]:
#create a numpy array with random array within specific range
R = np.random.randint(10,100,(3,5))
print(R)

[[70 64 60 84 79]
 [74 28 61 91 28]
 [32 35 93 45 26]]


In [ ]:
# creating array with evenly spaced values --> specifying the number of values
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,20,3)
print(e)

[10 13 16 19]


In [ ]:
# convert a list to numpy array
list_3 = [10,20,30]
np_arr = np.asarray(list_3)
print(np_arr)
type(np_arr)

[10 20 30]


numpy.ndarray

Analysing a numpy array

In [ ]:
arr = np.random.randint(10,60,(5,5))
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[[39 39 10 33 29]
 [37 26 39 44 56]
 [27 15 33 12 45]
 [55 11 56 41 38]
 [10 21 37 30 16]]
(5, 5)
2
25
int64


Mathematical operations on numpy array

In [ ]:
list1 = [1,2,3,4,5,6]
list2 = [3,5,6,7,8]
print(list1 + list2)

[1, 2, 3, 4, 5, 6, 3, 5, 6, 7, 8]


In [ ]:
a1 = np.linspace(10,50,5)
print(a1)
a2 = np.linspace(20,60,5)
print(a2)


[10. 20. 30. 40. 50.]
[20. 30. 40. 50. 60.]


In [ ]:
print(a1 + a2)
print(a2 - a1)
print(a1/a2)
print(a1*a2)

[ 30.  50.  70.  90. 110.]
[10. 10. 10. 10. 10.]
[0.5        0.66666667 0.75       0.8        0.83333333]
[ 200.  600. 1200. 2000. 3000.]


In [ ]:
print(np.add(a1,a2))

[ 30.  50.  70.  90. 110.]


In [ ]:
A = np.random.randint(10,20,(3,4))
print(A)
AT = np.transpose(A)
print(AT)

[[17 12 11 19]
 [12 17 16 13]
 [17 18 15 16]]
[[17 12 17]
 [12 17 18]
 [11 16 15]
 [19 13 16]]


**Slicing 2D arrays**

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10] , [3 , 5 , 7 , 9 , 1]])
print(arr[0:3, 2])

[3 8 7]


In [ ]:
print(arr[2,1:4])

[5 7 9]


Converting the data type of array using **astype**

In [ ]:
arr = np.array([0,3.4,5,7.7])
print(arr.astype(int))

[0 3 5 7]


In [ ]:
print(arr.astype(bool))

[False  True  True  True]
